In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [2]:
df=pd.read_csv("C:\\Users\\Purushoth\\Desktop\\Apple\\AAPL(ClosingVal-tomorrow).csv")

In [3]:
df.head()

Date      Open      High       Low      Volume     Close
0  1/2/1998  0.121652  0.145089  0.120536   718110400  0.141741
1  1/5/1998  0.147321  0.147879  0.135603   651873600  0.169085
2  1/6/1998  0.142299  0.178571  0.131696  1812473600  0.156250
3  1/7/1998  0.167969  0.169643  0.154576  1041622400  0.162388
4  1/8/1998  0.155692  0.166295  0.151228   774020800  0.162388

In [4]:
df.isna().sum()

Date      0
Open      0
High      0
Low       0
Volume    0
Close     0
dtype: int64

In [5]:
df.shape

(5844, 6)

In [6]:
train = df[:4675]
test = df[-1169:]

In [7]:
y = df['Close']
del df['Close']
del df['Date']

In [8]:
x = pd.DataFrame(df)  

In [9]:
x.shape

(5844, 4)

In [10]:
xtrain = x[:4675]
xtest = x[-1169:]

ytrain = y[:4675]
ytest = y[-1169:].values

In [11]:
xtrain.shape

(4675, 4)

In [12]:
ytrain.shape

(4675,)

In [13]:
xtest.shape

(1169, 4)

In [14]:
ytest.shape

(1169,)

In [15]:
scaler = MinMaxScaler(feature_range=(0, 1))
xtrain= pd.DataFrame(scaler.fit_transform(xtrain))

In [16]:
xtrain.head()

0         1         2         3
0  0.000000  0.000000  0.000000  0.091946
1  0.000766  0.000083  0.000460  0.082973
2  0.000616  0.001000  0.000341  0.240187
3  0.001383  0.000733  0.001040  0.135768
4  0.001016  0.000633  0.000938  0.099519

In [17]:
scaler = MinMaxScaler(feature_range=(0, 1))
xtest= pd.DataFrame(scaler.fit_transform(xtest))

In [18]:
xtest.head()

0         1         2         3
0  0.007207  0.000737  0.003175  0.223156
1  0.004579  0.000253  0.004839  0.187239
2  0.006211  0.000590  0.005940  0.159473
3  0.007674  0.004066  0.007884  0.290107
4  0.010323  0.005583  0.010001  0.165720

### Random Forest

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
rf = RandomForestRegressor()
rf.fit(xtrain, ytrain)

RandomForestRegressor()

In [21]:
rf_predictions = rf.predict(xtest)
rf_predictions

array([ 0.2204365 ,  0.24106241,  0.2548539 , ..., 27.56952497,
       27.766725  , 27.16065004])

In [22]:
def mda(ytest:np.ndarray,predicted:np.ndarray):
    """ Mean Directional Accuracy """
    return np.mean((np.sign(ytest[1:]-ytest[:-1])== np.sign(predicted[1:]- predicted[:-1])).astype(int))

In [23]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(ytest, rf_predictions))
print('Mean Squared Error:', metrics.mean_squared_error(ytest, rf_predictions))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(ytest, rf_predictions)))
print('Mean Directional Accuracy:', mda(ytest, rf_predictions))

Mean Absolute Error: 49.46321816190762
Mean Squared Error: 2899.735463446301
Root Mean Squared Error: 53.84919185509009
Mean Directional Accuracy: 0.4871575342465753


### XGBoost

In [24]:
from xgboost import XGBRegressor

In [25]:
xgb = XGBRegressor()
xgb.fit(xtrain,ytrain)

[16:00:06] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor()

In [26]:
xgb_predictions = xgb.predict(xtest)
xgb_predictions

array([ 0.22537774,  0.23528016,  0.24574071, ..., 27.241476  ,
       27.666075  , 27.049852  ], dtype=float32)

In [27]:
print('Mean Absolute Error:', metrics.mean_absolute_error(ytest, xgb_predictions))
print('Mean Squared Error:', metrics.mean_squared_error(ytest, xgb_predictions))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(ytest, xgb_predictions)))
print('Mean Directional Accuracy:', mda(ytest, xgb_predictions))

Mean Absolute Error: 49.46823548206028
Mean Squared Error: 2900.8540954886935
Root Mean Squared Error: 53.859577565078375
Mean Directional Accuracy: 0.4152397260273973


### SVM

In [28]:
from sklearn.svm import SVR

In [29]:
svm = SVR()
svm.fit(xtrain,ytrain)

SVR()

In [30]:
svm_predictions = svm.predict(xtest)
svm_predictions

array([ 0.44894481,  0.36728533,  0.35086433, ..., 26.47070316,
       27.34670544, 27.04285892])

In [31]:
print('Mean Absolute Error:', metrics.mean_absolute_error(ytest, svm_predictions))
print('Mean Squared Error:', metrics.mean_squared_error(ytest, svm_predictions))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(ytest, svm_predictions)))
print('Mean Directional Accuracy:', mda(ytest, svm_predictions))

Mean Absolute Error: 49.7149095755365
Mean Squared Error: 2952.991757850737
Root Mean Squared Error: 54.34143684013827
Mean Directional Accuracy: 0.4914383561643836
